////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Capability Contract: POST, PUT
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide a contract for consumer reference on use of this capability

== Name
POST, PUT

== Description
This capability provides functionality to add resources to the document root of this service. This service is meant to be called as a web services, and not as a STROMA compliant service. The STROMA compliant "add" capability of this service should be used if a STROMA compliant addition or update of a resource is desired (i.e for an orchestrated request).

== State Management
This service capability is stateless

== Owner
TBD

== Interface

=== Interface Classification
* synchronous
* HTTP

=== Expected Input

.Special URI rules

* The URI of the service request is utilized as the target resource location unless the *uri* parameter is specified

.Parameters

* *uri* [optional] If specified, this will be the path (relative to the document root of this service) where the resource will be written to
* The request body is assumed to be the resource payload unless one of the following is specified:
	** *payload* [optional] If specified, this will be used as the data to write to the resource, instead of the body (highest priority)
	** *source* [optional] URI (absolute file path or http request) If specified, the contents of the resource written will be copied from this location

.Meta Data

N/A

[NOTE]
The following are trivial examples to use as a reference. Please see STROMA/X-STROMA specification for details.

==== XML request variations
----
http://localhost:8080/cyclades/restfs/dir-one/dir-two/sample.txt?action=POST&data-type=xml&payload=sample%20payload
----

==== JSON request variations
----
http://localhost:8080/cycladesengine/restfs/dir-one/dir-two/sample.txt?action=POST&data-type=json&payload=sample%20payload
----

=== Expected Output

You can see in the output below that the entity containts the following fields:

* *status-code* corresponds to the HTTP status code
* *message* is either the resource engaged or an error message

[NOTE]
If the "raw-response" STROMA parameter is utilized, the HTTP response code of this request will be automatically set to the status-code field mentioned above

==== XML
----
<response service="restfs" action="POST" error-code="0">
<entity status-code="200" message="dir-one/dir-two/sample.txt"/>
</response>
----

==== JSON
----
{"error-code":"0","service":"restfs","action":"POST","data":{"root":{"entity":{"@status-code":"200","@message":"dir-one\/dir-two\/sample.txt"}}}}
----

== Additional Orchestration Capability Details

None

== Functional Requirements

* The capability will enable users to add resources to this service's document root. Although this capability is STROMA like, it differs in that the body of the request can be binary (non XML or JSON). If a fully STROMA compliant POST like capability is desired, please see the "add" capability of this service.

== Non Functional Requirements

* SLA/QoS
 - N/A

* Security
 - N/A

== Test Results

* link:load_test_results.html[Load Test Results]
* link:extended_duration_test_results.html[Extended Duration Test Results]
* link:functional_test_results.html[Functional Test Results]

== Modifications To This Document

[options="header"]
|=========================================================
|Author			|Date		|Version	|Details
|Tom Angelopoulos	|4/3/2012	|1.0		|Document Creation
|=========================================================
