////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Capability Contract: whoami
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide a contract for consumer reference on use of this capability

== Name
whoami

== Description
This capability echoes back the following sets of fields from a request:

* HTTP Headers (if any)
* HTTP Query Parameters (if any)
* STROMA Parameters (if any, and of requested with the "stroma" parameter)

== State Management
This service capability is stateless

== Owner
TBD

== Interface

=== Interface Classification
* STROMA
* synchronous
* HTTP

=== Expected Input

.Special URI rules

* N/A

.Parameters

*stroma* [optional] If present, the response will include the STROMA parameters.

.Meta Data

N/A

[NOTE]
The following are trivial examples to use as a reference. Please see STROMA/X-STROMA specification for details.

==== XML request variations
----
http://localhost:8080/cyclades/restfs?action=whoami&data-type=xml
----

==== JSON request variations
----
http://localhost:8080/cyclades/restfs?action=whoami&data-type=json
----

=== Expected Output

==== XML
----
<response service="restfs" action="whoami" error-code="0">
<http_method>GET</http_method>
<http_headers>
<header name="host">
<value>localhost:8080</value>
</header>
<header name="user-agent">
<value>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_1) AppleWebKit/534.48.3 (KHTML, like Gecko) Version/5.1 Safari/534.48.3
</value>
</header>
<header name="accept">
<value>
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
</value>
</header>
<header name="accept-language">
<value>en-us</value>
</header>
<header name="accept-encoding">
<value>gzip, deflate</value>
</header>
<header name="connection">
<value>keep-alive</value>
</header>
</http_headers>
<http_parameters>
<parameter name="data-type">
<value>xml</value>
</parameter>
<parameter name="action">
<value>whoami</value>
</parameter>
</http_parameters>
</response>
----

==== JSON
----
{"error-code":"0","service":"restfs","action":"whoami","data":{"root":{"http_method":{"$":"GET"},"http_headers":{"header":[{"@name":"host","value":{"$":"localhost:8080"}},{"@name":"user-agent","value":{"$":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_7_1) AppleWebKit\/534.48.3 (KHTML, like Gecko) Version\/5.1 Safari\/534.48.3"}},{"@name":"accept","value":{"$":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,*\/*;q=0.8"}},{"@name":"accept-language","value":{"$":"en-us"}},{"@name":"accept-encoding","value":{"$":"gzip, deflate"}},{"@name":"connection","value":{"$":"keep-alive"}}]},"http_parameters":{"parameter":[{"@name":"data-type","value":{"$":"json"}},{"@name":"action","value":{"$":"whoami"}}]}}}}
----

== Additional Orchestration Capability Details

None

== Functional Requirements

* This capability will essentially echo back fields in the service request for debugging purposes

== Non Functional Requirements

* SLA/QoS
 - N/A

* Security
 - N/A

== Test Results

* link:load_test_results.html[Load Test Results]
* link:extended_duration_test_results.html[Extended Duration Test Results]
* link:functional_test_results.html[Functional Test Results]

== Modifications To This Document

[options="header"]
|=========================================================
|Author			|Date		|Version	|Details
|Tom Angelopoulos	|4/3/2012	|1.0		|Document Creation
|=========================================================
